AddPrefabPostInit("firesuppressor", function(inst)
    inst:AddTag("absolute_guard")
    inst:AddTag("shelter")
    inst:AddTag("drive_bird_scarecrow")
    inst:AddTag("antlion_sinkhole_blocker")
    inst:AddTag("quake_blocker")
    inst:AddComponent("lightningblocker") 
    inst.components.lightningblocker:SetBlockRange(28)
end)